export const categories = [
  {
    id: "bitki-cajevi",
    name: "Biljni čajevi",
    slug: "bitki-cajevi",
    opis: "Umirujući, ljekoviti čajevi za svaki trenutak",
    image: "/hero/biljni caj.png",
    potkategorije: ["Opuštanje", "Probava", "Imunitet", "Ljepota", "Energija"],
  },
  {
    id: "ljekovite-biljke",
    name: "Ljekovite biljke",
    slug: "ljekovite-biljke",
    opis: "Tradicionalne biljke za svakodnevno zdravlje",
    image: "/hero/ljekovitobilje.png",
    potkategorije: ["Suhe biljke", "Mješavine", "Sjemenke", "Cvjetovi"],
  },
  {
    id: "zacini",
    name: "Začini",
    slug: "zacini",
    opis: "Ručno brani začini iz cijelog svijeta",
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&q=80",
    potkategorije: ["Mljeveni začini", "Cijeli začini", "Mješavine", "Soli i trljači"],
  },
  {
    id: "organski",
    name: "Organski proizvodi",
    slug: "organski",
    opis: "Čisto, certificirano organsko blago prirode",
    image: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&q=80",
    potkategorije: ["Organske biljke", "Organski začini", "Organsko ulje", "Organski med"],
  },
  {
    id: "ulja-arome",
    name: "Ulja i arome",
    slug: "ulja-arome",
    opis: "Eterična ulja i biljni ekstrakti",
    image: "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=800&q=80",
    potkategorije: ["Eterična ulja", "Bazna ulja", "Ulja za kosu", "Mješavine ulja"],
  },
  {
    id: "prirodna-hrana",
    name: "Prirodna hrana",
    slug: "prirodna-hrana",
    opis: "Cjelovita, minimalno obrađena prirodna hrana",
    image: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&q=80",
    potkategorije: ["Suho voće", "Sjemenke", "Žitarice", "Mahunarke"],
  },
  {
    id: "med-pcela",
    name: "Med i pčelinji proizvodi",
    slug: "med-pcela",
    opis: "Sirovi, čisti med i blago košnice",
    image: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=800&q=80",
    potkategorije: ["Sirovi med", "Matična mliječ", "Propolis", "Cvjetni prah"],
  },
  {
    id: "kozmetika",
    name: "Biljna kozmetika",
    slug: "kozmetika",
    opis: "Čista ljepota zahvaljujući prirodi",
    image: "https://images.unsplash.com/photo-1629198688000-71f23e745b6e?w=800&q=80",
    potkategorije: ["Šamponi", "Sapuni", "Njega kože", "Lična njega"],
  },
  {
    id: "dodaci-prehrani",
    name: "Dodaci prehrani",
    slug: "dodaci-prehrani",
    opis: "Naučno potvrđeni dodaci za vitalnost",
    image: "https://images.unsplash.com/photo-1512069772995-ec65ed45afd6?w=800&q=80",
    potkategorije: ["Ekstrakti", "Sirupi", "Kapsule", "Praškovi"],
  },
];

export const proizvodi = [
  {
    id: "1",
    naziv: "Lipa (List) 250g",
    kategorija: "bitki-cajevi",
    slug: "lipa-list-250g",
    cijena: 15.90,
    staraCijena: null,
    ocjena: 4.8,
    brojRecenzija: 142,
    oznaka: "Najprodavanije",
    slika: "/products/ihlamur-yaprak.jpg",
    slike: ["/products/ihlamur-yaprak.jpg"],
    opis: "Listovi lipe ubrani u vrhuncu sezone. Nudi mekši, uravnoteženiji napitak u usporedbi s cvjetnim varijantama. Idealan za one koji traže lakše iskustvo čaja. Bez konzervansa, umjetnih aroma ili boja.",
    sastojci: "100% sušeni listovi lipe (Tilia spp.)",
    upotreba: "1-2 kašičice u 200ml kipuće vode, kuhati 5-7 minuta.",
    prednosti: ["Smiruje grlo", "Zagrijavajuće svojstvo", "Bez konzervansa", "Prirodno"],
    naStanju: true,
    novinkat: false,
    organsko: false,
    tezina: "250g",
  },
  {
    id: "2",
    naziv: "Anis 150g",
    kategorija: "zacini",
    slug: "anis-150g",
    cijena: 4.50,
    staraCijena: null,
    ocjena: 4.6,
    brojRecenzija: 88,
    oznaka: null,
    slika: "/products/anason.jpg",
    slike: ["/products/anason.jpg"],
    opis: "Arifoğlu Anis je slatko-aromatični začin dobiven iz sjemenki biljke Pimpinella anisum. Koristi se u slatkišima, kolačićima, napicima i tijestu, dodajući svježinu i karakter jelima svojom karakterističnom aromom.",
    sastojci: "100% sjemenke anisa (Pimpinella anisum)",
    upotreba: "Koristite u pečenju, čajevima i kuharskim jelima po ukusu.",
    prednosti: ["Pomaže probavi", "Aromatično", "Prirodno", "Višenamjensko"],
    naStanju: true,
    novinkat: false,
    organsko: false,
    tezina: "150g",
  },
  {
    id: "3",
    naziv: "Hibiskus 100g",
    kategorija: "bitki-cajevi",
    slug: "hibiskus-100g",
    cijena: 5.90,
    staraCijena: 7.50,
    ocjena: 4.7,
    brojRecenzija: 203,
    oznaka: "Akcija",
    slika: "/products/hibiskus.jpg",
    slike: ["/products/hibiskus.jpg"],
    opis: "Hibiskus čaj s intenzivnom rubinsko-crvenom bojom i kiselkasto-svježim okusom. Bogat vitaminom C i antioksidansima. Može se piti toplo ili hladno kao ledeni čaj.",
    sastojci: "100% cvijet hibiskusa (Hibiscus sabdariffa)",
    upotreba: "1-2 kašičice u vrućoj vodi, kuhati 5 minuta. Odlično i hladno.",
    prednosti: ["Bogat vitaminom C", "Antioksidansi", "Svježi okus", "Podrška imunitetu"],
    naStanju: true,
    novinkat: false,
    organsko: false,
    tezina: "100g",
  },
  {
    id: "4",
    naziv: "Lavanda 100g",
    kategorija: "ljekovite-biljke",
    slug: "lavanda-100g",
    cijena: 6.50,
    staraCijena: null,
    ocjena: 4.9,
    brojRecenzija: 176,
    oznaka: "Najprodavanije",
    slika: "/products/lavanta.jpg",
    slike: ["/products/lavanta.jpg"],
    opis: "Lavanda je poludrvenasta višegodišnja biljka iz porodice Lamiaceae. Poznata po svojoj divnoj aromi, koristi se za čaj, eterično ulje, tinkturu, kolonju, sapun i šampon. Premium sastojak u industriji parfema.",
    sastojci: "100% cvjetovi lavande (Lavandula angustifolia)",
    upotreba: "Čaj: 1 kašičica na 200ml vrele vode. Aromaterapija: dodajte u kadu ili difuzor.",
    prednosti: ["Opuštajuće", "Pomaže spavanju", "Aromaterapija", "Višenamjensko"],
    naStanju: true,
    novinkat: false,
    organsko: false,
    tezina: "100g",
  },
  {
    id: "5",
    naziv: "Crni kim mljeveni 100g",
    kategorija: "zacini",
    slug: "crni-kim-mljeveni-100g",
    cijena: 6.50,
    staraCijena: null,
    ocjena: 4.9,
    brojRecenzija: 319,
    oznaka: "Najprodavanije",
    slika: "/products/corek-otu.jpg",
    slike: ["/products/corek-otu.jpg"],
    opis: "Mljeveni crni kim (Nigella sativa) - jedan od najmoćnijih prirodnih supernamirnica. Poznat u islamskoj tradiciji kao 'lijek za svaku bolest osim smrti'. Bogat timokvinonom i eteričnim uljima.",
    sastojci: "100% mljevene sjemenke crnog kima (Nigella sativa)",
    upotreba: "1 kašičica dnevno. Dodajte u jogurt, med, salate ili topla jela.",
    prednosti: ["Jača imunitet", "Protuupalno", "Bogato antioksidansima", "Tradicionalna medicina"],
    naStanju: true,
    novinkat: false,
    organsko: false,
    tezina: "100g",
  },
  {
    id: "6",
    naziv: "Ružmarin 120g",
    kategorija: "ljekovite-biljke",
    slug: "ruzmar-120g",
    cijena: 4.90,
    staraCijena: null,
    ocjena: 4.5,
    brojRecenzija: 94,
    oznaka: null,
    slika: "/products/biberiye.jpg",
    slike: ["/products/biberiye.jpg"],
    opis: "Sušeni ružmarin s intenzivnom aromatičnom mirisom. Nezamjenjiv začin u mediteranskoj kuhinji. Koristi se za čaj, u kuhanju mesa, povrća i kruha.",
    sastojci: "100% sušeni ružmarin (Rosmarinus officinalis)",
    upotreba: "U kuhanju: dodajte na meso, pečeno povrće, kruh. Za čaj: 1 kašičica u vrućoj vodi.",
    prednosti: ["Poboljšava pamćenje", "Antioksidansi", "Aromatično", "Višenamjensko"],
    naStanju: true,
    novinkat: false,
    organsko: false,
    tezina: "120g",
  },
  {
    id: "7",
    naziv: "Kopriva 50g",
    kategorija: "ljekovite-biljke",
    slug: "kopriva-50g",
    cijena: 5.50,
    staraCijena: null,
    ocjena: 4.6,
    brojRecenzija: 127,
    oznaka: null,
    slika: "/products/isirgan-otu.jpg",
    slike: ["/products/isirgan-otu.jpg"],
    opis: "Sušena kopriva (Urtica dioica) je jedna od najljekovitijih biljaka. Bogata željezom, vitaminima i mineralima. Tradicionalno se koristi za potporu zdravlja zglobova, kose i krvi.",
    sastojci: "100% sušeni listovi koprive (Urtica dioica)",
    upotreba: "1-2 kašičice u 200ml kipuće vode, kuhati 10 minuta. Piti 2-3 puta dnevno.",
    prednosti: ["Bogata željezom", "Podržava zglobove", "Jača kosu", "Pročišćava krv"],
    naStanju: true,
    novinkat: false,
    organsko: false,
    tezina: "50g",
  },
  {
    id: "8",
    naziv: "Kantarion 90g",
    kategorija: "ljekovite-biljke",
    slug: "kantarion-90g",
    cijena: 6.90,
    staraCijena: null,
    ocjena: 4.7,
    brojRecenzija: 88,
    oznaka: "Novo",
    slika: "/products/kantaron.jpg",
    slike: ["/products/kantaron.jpg"],
    opis: "Žuti kantarion (Hypericum perforatum) je tradicionalna ljekovita biljka poznata u narodnoj medicini. Suše se cvjetovi i listovi u punom cvatu.",
    sastojci: "100% sušeni cvjetovi i listovi kantariona (Hypericum perforatum)",
    upotreba: "1-2 kašičice u vrućoj vodi. Piti 1-2 puta dnevno.",
    prednosti: ["Tradicionalna medicina", "Prirodno", "Bez konzervansa", "Domaći proizvod"],
    naStanju: true,
    novinkat: true,
    organsko: false,
    tezina: "90g",
  },
  {
    id: "9",
    naziv: "Ulje matičnjaka 20ml",
    kategorija: "ulja-arome",
    slug: "ulje-matichnjaka-20ml",
    cijena: 8.90,
    staraCijena: 11.50,
    ocjena: 4.4,
    brojRecenzija: 52,
    oznaka: "Akcija",
    slika: "/products/melisa-yagi.jpg",
    slike: ["/products/melisa-yagi.jpg"],
    opis: "Eterično ulje matičnjaka dobiveno metodom destilacije vodenom parom. Poznat po umirujućim i opuštajućim svojstvima. Isključivo za vanjsku upotrebu.",
    sastojci: "100% eterično ulje matičnjaka (Melissa officinalis)",
    upotreba: "3 kapi razrijediti u baznom ulju za masažu. Isključivo za vanjsku upotrebu.",
    prednosti: ["Umiruje", "Aromaterapija", "Prirodno", "Destilirano parom"],
    naStanju: true,
    novinkat: false,
    organsko: false,
    tezina: "20ml",
  },
  {
    id: "10",
    naziv: "Majčina dušica 50g",
    kategorija: "ljekovite-biljke",
    slug: "majcina-dusica-50g",
    cijena: 4.50,
    staraCijena: null,
    ocjena: 4.8,
    brojRecenzija: 234,
    oznaka: "Najprodavanije",
    slika: "/products/kekik.jpg",
    slike: ["/products/kekik.jpg"],
    opis: "Sušena majčina dušica (Thymus vulgaris) - nezaobilazna biljka u svakom domu. Intenzivnog mirisa i okusa. Koristi se u kuhanju i kao biljni čaj s umirujućim djelovanjem na dišne putove.",
    sastojci: "100% sušena majčina dušica (Thymus vulgaris)",
    upotreba: "Za čaj: 1 kašičica u vrućoj vodi. U kuhanju: dodajte na meso, juhe, umake.",
    prednosti: ["Pomaže dišnim putovima", "Antiseptično", "Aromatično", "Višenamjensko"],
    naStanju: true,
    novinkat: false,
    organsko: false,
    tezina: "50g",
  },
  {
    id: "11",
    naziv: "Ruža pupoljci 90g",
    kategorija: "bitki-cajevi",
    slug: "ruza-pupoljci-90g",
    cijena: 12.90,
    staraCijena: 15.00,
    ocjena: 4.9,
    brojRecenzija: 167,
    oznaka: "Premium",
    slika: "/products/gul-tomurcuk.jpg",
    slike: ["/products/gul-tomurcuk.jpg"],
    opis: "Sušeni pupoljci ruže savršene arome i boje. Koriste se za premium biljni čaj, dekoraciju i aromaterapiju. Nježno i elegantno, potpuno prirodno.",
    sastojci: "100% sušeni pupoljci ruže (Rosa damascena)",
    upotreba: "5-7 pupoljaka u vrućoj vodi, kuhati 5-8 minuta. Odlično s medom.",
    prednosti: ["Prirodna aroma", "Bogat antioksidansima", "Ljepota kože", "Opuštajuće"],
    naStanju: true,
    novinkat: false,
    organsko: false,
    tezina: "90g",
  },
  {
    id: "12",
    naziv: "Mate čaj 200g",
    kategorija: "bitki-cajevi",
    slug: "mate-caj-200g",
    cijena: 10.50,
    staraCijena: null,
    ocjena: 4.5,
    brojRecenzija: 73,
    oznaka: "Novo",
    slika: "/products/mate-caj.jpg",
    slike: ["/products/mate-caj.jpg"],
    opis: "Tradicionalni južnoamerički biljni čaj napravljen od listova mate (Ilex paraguariensis). Bogat kofenom, antioksidansima i mineralima. Prirodni energetski napitak bez nervoznosti.",
    sastojci: "100% lišće mate (Ilex paraguariensis)",
    upotreba: "1-2 kašike u 200ml vrele vode na 70-80°C. Kuhati 3-5 minuta.",
    prednosti: ["Prirodna energija", "Bogat antioksidansima", "Poboljšava fokus", "Bez nervoznosti"],
    naStanju: true,
    novinkat: true,
    organsko: false,
    tezina: "200g",
  },
  {
    id: "13",
    naziv: "Šafran (kutija) 2g",
    kategorija: "zacini",
    slug: "safran-2g",
    cijena: 28.90,
    staraCijena: null,
    ocjena: 4.9,
    brojRecenzija: 58,
    oznaka: "Premium",
    slika: "/products/safran.jpg",
    slike: ["/products/safran.jpg"],
    opis: "Arifoğlu Šafran, skupocjeni začin pažljivo prikupljen sušenjem prašnika cvijeta Crocus sativus. Jedan od najskupljih začina na svijetu. Koristi se u pilafu, slatkišima i mliječnim napicima.",
    sastojci: "100% šafran (Crocus sativus)",
    upotreba: "Namočite 10-15 niti u 2 kašike tople vode 20 min. Dodajte u jela na kraju.",
    prednosti: ["Jedinstven okus", "Zlatna boja", "Premium kvalitet", "Antioksidansi"],
    naStanju: true,
    novinkat: false,
    organsko: false,
    tezina: "2g",
  },
  {
    id: "14",
    naziv: "Kurkuma mljevena 80g",
    kategorija: "zacini",
    slug: "kurkuma-mljevena-80g",
    cijena: 3.90,
    staraCijena: null,
    ocjena: 4.7,
    brojRecenzija: 289,
    oznaka: "Najprodavanije",
    slika: "/products/zerdecal.jpg",
    slike: ["/products/zerdecal.jpg"],
    opis: "Mljevena kurkuma zlatno-žute boje, prirodni začin biljke Curcuma longa. Nezaobilazna u soups, rižotima, umacima i povrću. Bogata kurkuminom - snažnim antioksidansom.",
    sastojci: "100% mljevena kurkuma (Curcuma longa)",
    upotreba: "Dodajte u juhe, rižu, curry, smoothie. Kombinujte s crnim biberom za bolju apsorpciju.",
    prednosti: ["Bogata kurkuminom", "Protuupalno", "Antioksidansi", "Zlatna mlijeko"],
    naStanju: true,
    novinkat: false,
    organsko: false,
    tezina: "80g",
  },
  {
    id: "15",
    naziv: "Cimet mljeveni 50g",
    kategorija: "zacini",
    slug: "cimet-mljeveni-50g",
    cijena: 3.20,
    staraCijena: null,
    ocjena: 4.6,
    brojRecenzija: 198,
    oznaka: null,
    slika: "/products/tarcin.jpg",
    slike: ["/products/tarcin.jpg"],
    opis: "Arifoğlu mljeveni cimet blagog i toplog okusa. Savršen za slatka i slana jela, čaj, kavu i pečivá. Jedan od najomiljenijih začina u bosanskoj kuhinji.",
    sastojci: "100% mljevena cimet (Cinnamomum verum)",
    upotreba: "Pospite na kafu, čaj, joghurt, pečivá ili dodajte u jela od mesa.",
    prednosti: ["Reguluje šećer u krvi", "Antioksidansi", "Topla aroma", "Višenamjensko"],
    naStanju: true,
    novinkat: false,
    organsko: false,
    tezina: "50g",
  },
  {
    id: "16",
    naziv: "Đumbir mljeveni 40g",
    kategorija: "zacini",
    slug: "dzumbir-mljeveni-40g",
    cijena: 2.80,
    staraCijena: null,
    ocjena: 4.7,
    brojRecenzija: 156,
    oznaka: null,
    slika: "/products/zencefil.jpg",
    slike: ["/products/zencefil.jpg"],
    opis: "Mljeveni korijen đumbira (Zingiber officinale) oštrog i pikantnong okusa. Idealan za čaj, kolače, curryje i marinade. Tradicionalno korišten za mučninu i prehlade.",
    sastojci: "100% mljeveni korijen đumbira (Zingiber officinale)",
    upotreba: "Za čaj: 1/2 kašičice u vrućoj vodi s limunom i medom. U kuhanju: dodajte po ukusu.",
    prednosti: ["Pomaže pri mučnini", "Protuupalno", "Grije tijelo", "Probava"],
    naStanju: true,
    novinkat: false,
    organsko: false,
    tezina: "40g",
  },
  {
    id: "17",
    naziv: "Kamilica 60g",
    kategorija: "bitki-cajevi",
    slug: "kamilica-60g",
    cijena: 9.50,
    staraCijena: 11.00,
    ocjena: 4.8,
    brojRecenzija: 312,
    oznaka: "Najprodavanije",
    slika: "/products/papatya.jpg",
    slike: ["/products/papatya.jpg"],
    opis: "Premium kamilica ubrana u maju, kada su cvjetovi na vrhuncu svojih aktivnih tvari. Poznatog umirujućeg okusa i mirisa, idealna za večernji ritual opuštanja.",
    sastojci: "100% sušeni cvjetovi kamilice (Matricaria chamomilla)",
    upotreba: "1-2 kašičice u 200ml vrele vode, kuhati 5-7 minuta.",
    prednosti: ["Umiruje", "Pomaže spavanju", "Smiruje probavu", "Prirodno"],
    naStanju: true,
    novinkat: false,
    organsko: false,
    tezina: "60g",
  },
  {
    id: "18",
    naziv: "Lipa (Cvijet) 250g",
    kategorija: "bitki-cajevi",
    slug: "lipa-cvijet-250g",
    cijena: 48.90,
    staraCijena: null,
    ocjena: 4.9,
    brojRecenzija: 89,
    oznaka: "Premium",
    slika: "/products/ihlamur-cicek.jpg",
    slike: ["/products/ihlamur-cicek.jpg"],
    opis: "Premium cvjetovi lipe paažljivo ubrani i sušeni. Intenzivniji, cvjetniji okus od listnih varijanti. Tradicionalni zimski čaj za grijanje i zaštitu od prehlade.",
    sastojci: "100% sušeni cvjetovi lipe (Tilia spp.)",
    upotreba: "1-2 kašičice u 200ml kipuće vode, kuhati 8-10 minuta. S medom po ukusu.",
    prednosti: ["Grije tijelo", "Zaštita od prehlade", "Snažna aroma", "Tradicionalno"],
    naStanju: true,
    novinkat: false,
    organsko: false,
    tezina: "250g",
  },
  {
    id: "19",
    naziv: "Morač 130g",
    kategorija: "zacini",
    slug: "morach-130g",
    cijena: 4.90,
    staraCijena: null,
    ocjena: 4.4,
    brojRecenzija: 67,
    oznaka: null,
    slika: "/products/rezene.jpg",
    slike: ["/products/rezene.jpg"],
    opis: "Aromatični morač (Foeniculum vulgare) - začin dobiven iz sjemenki biljke. Blago slatkog, anisastog okusa. Odličan kao čaj za probavu ili začin u kuhanju.",
    sastojci: "100% sjemenke morača (Foeniculum vulgare)",
    upotreba: "Za čaj: kuhati 1 kašičicu 5-10 minuta. U kuhanju: dodajte u ribe, kruh, salate.",
    prednosti: ["Pomaže probavi", "Osvježavajuće", "Prirodno", "Aromatično"],
    naStanju: true,
    novinkat: false,
    organsko: false,
    tezina: "130g",
  },
  {
    id: "20",
    naziv: "Zeleni čaj pupoljci 150g",
    kategorija: "bitki-cajevi",
    slug: "zeleni-caj-pupoljci-150g",
    cijena: 9.90,
    staraCijena: null,
    ocjena: 4.7,
    brojRecenzija: 145,
    oznaka: "Novo",
    slika: "/products/yesil-cay.jpg",
    slike: ["/products/yesil-cay.jpg"],
    opis: "Premium pupoljci zelenog čaja (Camellia sinensis) pažljivo brani i minimalnu obrađeni. Najbogatija koncentracija antioksidanasa i EGCG komponenti. Nježan, svježi okus.",
    sastojci: "100% pupoljci zelenog čaja (Camellia sinensis)",
    upotreba: "1 kašičica u vodi 70-80°C (ne kipuće!), kuhati 2-3 minute.",
    prednosti: ["Bogat antioksidansima", "Prirodna energija", "Metabolism", "Fokus"],
    naStanju: true,
    novinkat: true,
    organsko: false,
    tezina: "150g",
  },
  {
    id: "21",
    naziv: "List masline 120g",
    kategorija: "ljekovite-biljke",
    slug: "list-masline-120g",
    cijena: 5.90,
    staraCijena: null,
    ocjena: 4.6,
    brojRecenzija: 98,
    oznaka: null,
    slika: "/products/zeytin-yapragi.jpg",
    slike: ["/products/zeytin-yapragi.jpg"],
    opis: "Sušeni listovi masline (Olea europaea) bogati oleuropeinom. Tradicionalno korišten u mediteranskim kulturama. Blago gorkog, travnatog okusa.",
    sastojci: "100% sušeni listovi masline (Olea europaea)",
    upotreba: "1 kašičica u 200ml kipuće vode, kuhati 10 minuta. Piti 2x dnevno.",
    prednosti: ["Oleuropein", "Antioksidansi", "Tradicionlna medicina", "Mediteranska biljka"],
    naStanju: true,
    novinkat: false,
    organsko: false,
    tezina: "120g",
  },
  {
    id: "22",
    naziv: "Chia sjemenke 500g",
    kategorija: "prirodna-hrana",
    slug: "chia-sjemenke-500g",
    cijena: 9.90,
    staraCijena: 12.00,
    ocjena: 4.8,
    brojRecenzija: 267,
    oznaka: "Akcija",
    slika: "/products/chia.jpg",
    slike: ["/products/chia.jpg"],
    opis: "Chia sjemenke (Salvia hispanica) - moćna supernamirnica bogata omega-3, vlaknima, proteinima i mineralima. Bez okusa, lako se dodaje u smoothije, jogurt, pudinzi.",
    sastojci: "100% chia sjemenke (Salvia hispanica)",
    upotreba: "1-2 kašike dnevno u smoothiju, jogurtu, ovsu ili pudingu. Natopiti u vodi 15 min.",
    prednosti: ["Omega-3 masne kiseline", "Bogata vlaknima", "Proteini", "Bez glutena"],
    naStanju: true,
    novinkat: false,
    organsko: false,
    tezina: "500g",
  },
  {
    id: "23",
    naziv: "Štapići vanile 10 kom",
    kategorija: "zacini",
    slug: "stapici-vanile-10-kom",
    cijena: 24.90,
    staraCijena: null,
    ocjena: 4.8,
    brojRecenzija: 74,
    oznaka: "Premium",
    slika: "/products/vanilya.jpg",
    slike: ["/products/vanilya.jpg"],
    opis: "Premium štapići vanile u elegantnoj kutiji. Intenzivna, prirodna aroma vanile. Savršeni za kolače, kreme, sladolede i ostale deserti.",
    sastojci: "100% sušeni mahune vanile (Vanilla planifolia)",
    upotreba: "Presjeci mahunu, izvadite sjemenke i dodajte u tijesta, kreme ili tople napitke.",
    prednosti: ["Prirodna aroma", "Premium kvalitet", "Intenzivan okus", "Višenamjensko"],
    naStanju: true,
    novinkat: false,
    organsko: false,
    tezina: "10 kom",
  },
  {
    id: "24",
    naziv: "Matičnjak 25g",
    kategorija: "ljekovite-biljke",
    slug: "mathichnjak-25g",
    cijena: 5.50,
    staraCijena: null,
    ocjena: 4.5,
    brojRecenzija: 111,
    oznaka: null,
    slika: "/products/melisa.jpg",
    slike: ["/products/melisa.jpg"],
    opis: "Matičnjak (Melissa officinalis) - višegodišnja biljka aromatičnog limunastog mirisa iz porodice metvice. Porijeklom iz Mediterana. Čaj od matičnjaka poznate je umirujuće svojstvo.",
    sastojci: "100% sušeni listovi matičnjaka (Melissa officinalis)",
    upotreba: "1-2 kašičice u 200ml kipuće vode, kuhati 5-7 minuta.",
    prednosti: ["Umiruje nervozu", "Pomaže spavanju", "Limunasta aroma", "Prirodno"],
    naStanju: true,
    novinkat: false,
    organsko: false,
    tezina: "25g",
  },
  {
    id: "25",
    naziv: "Majčin čaj 200g",
    kategorija: "bitki-cajevi",
    slug: "majcin-caj-200g",
    cijena: 7.90,
    staraCijena: null,
    ocjena: 4.6,
    brojRecenzija: 83,
    oznaka: "Novo",
    slika: "/products/anne-caj.jpg",
    slike: ["/products/anne-caj.jpg"],
    opis: "Posebna mješavina biljaka za dojilje i trudnice. Sadrži muškatni oraščić, morač, korijander, anis, kim i koprivu. Tradicionalno korišten za potporu laktacije.",
    sastojci: "Muškatni oraščić, morač, korijander, anis, kim, kopriva",
    upotreba: "1-2 kašičice u 200ml kipuće vode, kuhati 7-10 minuta. Max 2-3 šalice dnevno.",
    prednosti: ["Podržava laktaciju", "Prirodno", "Mješavina biljaka", "Tradicionalno"],
    naStanju: true,
    novinkat: true,
    organsko: false,
    tezina: "200g",
  },
  {
    id: "26",
    naziv: "Artičoka 80g",
    kategorija: "ljekovite-biljke",
    slug: "articoka-80g",
    cijena: 5.90,
    staraCijena: null,
    ocjena: 4.5,
    brojRecenzija: 62,
    oznaka: null,
    slika: "/products/enginar.jpg",
    slike: ["/products/enginar.jpg"],
    opis: "Sušene kore i listovi artičoke (Cynara scolymus) tradicionalno korišten za potporu rada jetre i žučnog mjehura. Blago gorkog, travnatog okusa.",
    sastojci: "100% sušene kore i listovi artičoke (Cynara scolymus)",
    upotreba: "1 kašičica u 200ml kipuće vode, kuhati 10 minuta. Piti jednu šalicu dnevno.",
    prednosti: ["Podržava jetru", "Žučni mjehur", "Tradiconalna medicina", "Prirodno"],
    naStanju: true,
    novinkat: false,
    organsko: false,
    tezina: "80g",
  },
  {
    id: "27",
    naziv: "Susam 80g",
    kategorija: "prirodna-hrana",
    slug: "susam-80g",
    cijena: 2.50,
    staraCijena: null,
    ocjena: 4.4,
    brojRecenzija: 134,
    oznaka: null,
    slika: "/products/susam.jpg",
    slike: ["/products/susam.jpg"],
    opis: "Bijeli susam (Sesamum indicum) bogat kalcijem, željezom i zdravim mastima. Savršen za posipanje po kruhu, salatama, sushiju i kolačima.",
    sastojci: "100% bijeli susam (Sesamum indicum)",
    upotreba: "Pospite na kruh, salate ili sushi. Koristite za pravljenje tahinija.",
    prednosti: ["Bogat kalcijem", "Zdrave masti", "Proteini", "Višenamjensko"],
    naStanju: true,
    novinkat: false,
    organsko: false,
    tezina: "80g",
  },
  {
    id: "28",
    naziv: "Klinčić cijeli 15g",
    kategorija: "zacini",
    slug: "klincich-cijeli-15g",
    cijena: 3.90,
    staraCijena: null,
    ocjena: 4.7,
    brojRecenzija: 145,
    oznaka: null,
    slika: "/products/karanfil.jpg",
    slike: ["/products/karanfil.jpg"],
    opis: "Sušeni pupoljci drva Syzygium aromaticum intenzivne arome. Koriste se u slatkišima, toplim napicima, jelima od mesa i kiselim krastavčićima. Jedno od najstarijih začinaka.",
    sastojci: "100% cijeli klinčić (Syzygium aromaticum)",
    upotreba: "Dodajte u vreli čaj, kompot, marinadu ili jela od mesa. Koristite štedljivo.",
    prednosti: ["Intenzivna aroma", "Eugenol", "Antiseptično", "Višenamjensko"],
    naStanju: true,
    novinkat: false,
    organsko: false,
    tezina: "15g",
  },
  {
    id: "29",
    naziv: "Zahter 90g",
    kategorija: "ljekovite-biljke",
    slug: "zahter-90g",
    cijena: 6.50,
    staraCijena: null,
    ocjena: 4.8,
    brojRecenzija: 192,
    oznaka: "Najprodavanije",
    slika: "/products/zahter.jpg",
    slike: ["/products/zahter.jpg"],
    opis: "Zahter (Satureja) - aromatična ljekovita biljka iz mediteranskih krajeva. Poznat u bosanskoj tradiciji. Koristi se kao začin i biljni čaj s antibakterijskim svojstvima.",
    sastojci: "100% sušeni zahter (Satureja montana)",
    upotreba: "Za čaj: 1 kašičica u vrućoj vodi. Za kuhanje: dodajte na meso, grah, salate.",
    prednosti: ["Antibakterijsko", "Aromatično", "Tradicija BiH", "Probava"],
    naStanju: true,
    novinkat: false,
    organsko: false,
    tezina: "90g",
  },
  {
    id: "30",
    naziv: "Cikorija 70g",
    kategorija: "ljekovite-biljke",
    slug: "cikorija-70g",
    cijena: 2.50,
    staraCijena: null,
    ocjena: 4.3,
    brojRecenzija: 56,
    oznaka: null,
    slika: "/products/hindiba.jpg",
    slike: ["/products/hindiba.jpg"],
    opis: "Cikorija (Cichorium intybus) - ljekovita biljka tradicionalno korišten za potporu zdravlja jetre i žučnog mjehura. Lagan, blago gorak okus.",
    sastojci: "100% sušeni korijen i listovi cikorije (Cichorium intybus)",
    upotreba: "1 kašičica u 200ml kipuće vode, kuhati 10 minuta.",
    prednosti: ["Jetra i žuč", "Probava", "Tradiconalna medicina", "Prirodno"],
    naStanju: true,
    novinkat: false,
    organsko: false,
    tezina: "70g",
  },
  {
    id: "31",
    naziv: "Ginkgo Biloba 100g",
    kategorija: "dodaci-prehrani",
    slug: "ginkgo-biloba-100g",
    cijena: 8.20,
    staraCijena: null,
    ocjena: 4.7,
    brojRecenzija: 63,
    oznaka: "Premium",
    slika: "/products/ginkgo-biloba.jpg",
    slike: ["/products/ginkgo-biloba.jpg"],
    opis: "Ginkgo biloba — jedno od najstarijih stabala na Zemlji. Tradiconalno se koristi za poboljšanje cirkulacije i kognitivnih funkcija. Pogodno kao prirodni dodatak prehrani.",
    sastojci: "100% sušeni listovi ginkgo biloba (Ginkgo biloba L.)",
    upotreba: "1 kašičica u 250ml kipuće vode, kuhati 10 minuta. Maksimalno 2 šolje dnevno.",
    prednosti: ["Cirkulacija", "Koncentracija", "Antioksidansi", "Memorija"],
    naStanju: true,
    novinkat: false,
    organsko: false,
    tezina: "100g",
  },
  {
    id: "32",
    naziv: "Enginar (List i kora) 50g",
    kategorija: "dodaci-prehrani",
    slug: "enginar-list-50g",
    cijena: 7.50,
    staraCijena: null,
    ocjena: 4.6,
    brojRecenzija: 41,
    oznaka: null,
    slika: "/products/enginar.jpg",
    slike: ["/products/enginar.jpg"],
    opis: "Artičoka (Cynara scolymus) — prirodni saveznik jetre i probave. Bere se u Egejskoj, Mramornomorskoj i mediteranskoj regiji. Bez konzervansa.",
    sastojci: "100% sušeni listovi i kora artičoke (Cynara scolymus)",
    upotreba: "1–2 kašičice u 200ml kipuće vode, kuhati 10 minuta. Piti jednom dnevno.",
    prednosti: ["Jetra i žuč", "Probava", "Kolesterol", "Detoksikacija"],
    naStanju: true,
    novinkat: false,
    organsko: false,
    tezina: "50g",
  },
  {
    id: "33",
    naziv: "Kopriva (Sjeme mljeveno) 100g",
    kategorija: "dodaci-prehrani",
    slug: "kopriva-sjeme-100g",
    cijena: 11.70,
    staraCijena: null,
    ocjena: 4.8,
    brojRecenzija: 88,
    oznaka: "Najprodavanije",
    slika: "/products/isirgan-tohumu.jpg",
    slike: ["/products/isirgan-tohumu.jpg"],
    opis: "Mljeveno sjeme koprive (Urtica dioica) — bogato željezom, vitaminima i mineralima. Koristi se u tradicionalnoj medicini za vitalnost i energiju.",
    sastojci: "100% mljeveno sjeme koprive (Urtica dioica)",
    upotreba: "1 kašičica dnevno pomiješana u jogurt, smoothie ili med.",
    prednosti: ["Energija", "Željezo", "Hormoni", "Vitalnost"],
    naStanju: true,
    novinkat: false,
    organsko: true,
    tezina: "100g",
  },
  {
    id: "34",
    naziv: "Maslinov list 120g",
    kategorija: "dodaci-prehrani",
    slug: "maslinov-list-120g",
    cijena: 7.50,
    staraCijena: null,
    ocjena: 4.7,
    brojRecenzija: 55,
    oznaka: null,
    slika: "/products/zeytin-yaprak.jpg",
    slike: ["/products/zeytin-yaprak.jpg"],
    opis: "Maslinov list (Olea europaea) — sveto stablo čovječanstva. Listovi su bogati oleuropeinom, snažnim antioksidansom. Prirodna podrška imunitetu i krvnom tlaku.",
    sastojci: "100% sušeni listovi masline (Olea europaea)",
    upotreba: "1 kašičica u 200ml kipuće vode, kuhati 10 minuta. 1–2 šolje dnevno.",
    prednosti: ["Imunitet", "Krvni pritisak", "Antioksidansi", "Srce"],
    naStanju: true,
    novinkat: true,
    organsko: false,
    tezina: "120g",
  },
  {
    id: "35",
    naziv: "Ulje matičnjaka 20ml",
    kategorija: "kozmetika",
    slug: "ulje-maticnjaka-20ml",
    cijena: 10.50,
    staraCijena: 13.90,
    ocjena: 4.9,
    brojRecenzija: 76,
    oznaka: "Akcija",
    slika: "/products/melisa-yagi.jpg",
    slike: ["/products/melisa-yagi.jpg"],
    opis: "Prirodno eterično ulje matičnjaka dobijeno parnom destilacijom. Omekšava, hidratizira i njeguje kožu. Idealno za masažu ili kao dodatak baznom ulju.",
    sastojci: "100% prirodno eterično ulje matičnjaka (Melissa officinalis)",
    upotreba: "Vanjska primjena: nanesite malu količinu na čistu kožu masažom. Razrijedite u baznom ulju prije primjene.",
    prednosti: ["Hidratacija kože", "Opuštanje", "Njega kože", "Prirodno"],
    naStanju: true,
    novinkat: false,
    organsko: true,
    tezina: "20ml",
  },
  {
    id: "36",
    naziv: "Ulje lavande 20ml",
    kategorija: "kozmetika",
    slug: "ulje-lavande-20ml",
    cijena: 9.90,
    staraCijena: null,
    ocjena: 4.8,
    brojRecenzija: 112,
    oznaka: "Najprodavanije",
    slika: "/products/lavanta.jpg",
    slike: ["/products/lavanta.jpg"],
    opis: "Eterično ulje lavande — klasik u prirodnoj kozmetici i aromaterapiji. Umiruje, relaksira i pomaže kod suhoj koži. Čistoće 100%.",
    sastojci: "100% eterično ulje lavande (Lavandula angustifolia)",
    upotreba: "Dodajte 3–5 kapi u difuzor ili razrijedite u 10ml baznog ulja za masažu.",
    prednosti: ["Aromaterapija", "Opuštanje", "Njega kože", "San"],
    naStanju: true,
    novinkat: false,
    organsko: true,
    tezina: "20ml",
  },
  {
    id: "37",
    naziv: "Ruža (Tomurcuk) 90g",
    kategorija: "kozmetika",
    slug: "ruza-tomurcuk-kozmetika",
    cijena: 12.90,
    staraCijena: null,
    ocjena: 4.9,
    brojRecenzija: 94,
    oznaka: "Premium",
    slika: "/products/gul-tomurcuk.jpg",
    slike: ["/products/gul-tomurcuk.jpg"],
    opis: "Sušeni pupoljci ruže (Rosa sp.) — bogati vitaminom C i antioksidansima. Koriste se za čajeve, infuzije i prirodnu njegu kože. Ubrani u vrhuncu cvjetanja.",
    sastojci: "100% sušeni pupoljci ruže (Rosa sp.)",
    upotreba: "Za čaj: 1 kašičica u 200ml kipuće vode, 5–7 minuta. Za njegu kože: dodajte u toplu kupku.",
    prednosti: ["Vitamin C", "Antioksidansi", "Njega kože", "Imunitet"],
    naStanju: true,
    novinkat: false,
    organsko: true,
    tezina: "90g",
  },
  {
    id: "38",
    naziv: "Organski ihlamur 100g",
    kategorija: "organski",
    slug: "organski-ihlamur-100g",
    cijena: 13.50,
    staraCijena: null,
    ocjena: 4.9,
    brojRecenzija: 67,
    oznaka: "Organsko",
    slika: "/products/ihlamur-yaprak.jpg",
    slike: ["/products/ihlamur-yaprak.jpg"],
    opis: "Certificirano organski uzgojena lipa — bez pesticida, bez GMO. Posebno brana u planinskim predjelima Anadolije. Idealna za zimske večeri i opuštanje.",
    sastojci: "100% organski sušeni listovi lipe (Tilia spp.) — EU organic certified",
    upotreba: "1–2 kašičice u 200ml kipuće vode, 5–7 minuta. Dodajte med po ukusu.",
    prednosti: ["Bez pesticida", "EU organsko", "Opuštanje", "Imunitet"],
    naStanju: true,
    novinkat: false,
    organsko: true,
    tezina: "100g",
  },
  {
    id: "39",
    naziv: "Organska kamilica 60g",
    kategorija: "organski",
    slug: "organska-kamilica-60g",
    cijena: 11.90,
    staraCijena: null,
    ocjena: 4.8,
    brojRecenzija: 83,
    oznaka: "Organsko",
    slika: "/products/papatya.jpg",
    slike: ["/products/papatya.jpg"],
    opis: "Kamilica uzgojena po EU organskim standardima — bez kemikalija i umjetnih tretmana. Nježan, jabučast okus i umirujuće djelovanje.",
    sastojci: "100% organski sušeni cvjetovi kamilice (Matricaria chamomilla) — EU organic certified",
    upotreba: "1 kašičica cvjetova u 200ml kipuće vode, 5 minuta. 1–3 šolje dnevno.",
    prednosti: ["EU organsko", "Bez pesticida", "Umirujuće", "Probava"],
    naStanju: true,
    novinkat: false,
    organsko: true,
    tezina: "60g",
  },
  {
    id: "40",
    naziv: "Organska lavanda 50g",
    kategorija: "organski",
    slug: "organska-lavanda-50g",
    cijena: 10.50,
    staraCijena: null,
    ocjena: 4.7,
    brojRecenzija: 51,
    oznaka: "Organsko",
    slika: "/products/lavanta.jpg",
    slike: ["/products/lavanta.jpg"],
    opis: "Lavanda (Lavandula angustifolia) uzgojena po organskim principima. Cvjetovi brani ručno u Anadoliji. Savršena za čaj, aromaterapiju i jastučiće za spavanje.",
    sastojci: "100% organski sušeni cvjetovi lavande (Lavandula angustifolia)",
    upotreba: "Za čaj: 1 kašičica u 200ml kipuće vode, 5–7 minuta. Za aromaterapiju: dodajte u difuzor.",
    prednosti: ["EU organsko", "Aromaterapija", "San", "Opuštanje"],
    naStanju: true,
    novinkat: true,
    organsko: true,
    tezina: "50g",
  },
  {
    id: "41",
    naziv: "Propolis tinktura 30ml",
    kategorija: "med-pcela",
    slug: "propolis-tinktura-30ml",
    cijena: 18.90,
    staraCijena: null,
    ocjena: 4.9,
    brojRecenzija: 134,
    oznaka: "Najprodavanije",
    slika: "/products/melisa-yagi.jpg",
    slike: ["/products/melisa-yagi.jpg"],
    opis: "Prirodna propolis tinktura — snažan antibakterijski i antivirusni prirodni preparat. Pčele ga koriste za zaštitu košnice, a mi za zaštitu imuniteta.",
    sastojci: "Ekstrakt propolisa, etanol 70%",
    upotreba: "10–20 kapi razrijediti u čaši vode i popiti jednom dnevno, po mogućnosti ujutro.",
    prednosti: ["Imunitet", "Antibakterijsko", "Antiviralno", "Prirodno"],
    naStanju: true,
    novinkat: false,
    organsko: true,
    tezina: "30ml",
  },
  {
    id: "42",
    naziv: "Cvjetni prah (Polen) 100g",
    kategorija: "med-pcela",
    slug: "cvjetni-prah-100g",
    cijena: 16.50,
    staraCijena: null,
    ocjena: 4.8,
    brojRecenzija: 89,
    oznaka: "Premium",
    slika: "/products/gul-tomurcuk.jpg",
    slike: ["/products/gul-tomurcuk.jpg"],
    opis: "Svježi cvjetni prah sakupljen od pčela s anatolijskih livada. Bogat proteinima, vitaminima B i enzimima. Superfood iz košnice za vašu svakodnevnu rutinu.",
    sastojci: "100% prirodni cvjetni prah (pollen)",
    upotreba: "1 kašičica ujutro, može se pomiješati s medom, jogurtom ili sokom. Čuvati na hladnom i suhom.",
    prednosti: ["Proteini", "Vitamini B", "Energija", "Imunitet"],
    naStanju: true,
    novinkat: true,
    organsko: true,
    tezina: "100g",
  },
  {
    id: "43",
    naziv: "Matična mliječ 20g",
    kategorija: "med-pcela",
    slug: "maticna-mlijec-20g",
    cijena: 24.90,
    staraCijena: null,
    ocjena: 4.9,
    brojRecenzija: 47,
    oznaka: "Premium",
    slika: "/products/ihlamur-cicek.jpg",
    slike: ["/products/ihlamur-cicek.jpg"],
    opis: "Svježa matična mliječ — hrana pčelinje matice i jedan od najcjenjenijih prirodnih preparata. Bogata proteinima, masnim kiselinama i 10-HDA. Čuvati u frižideru.",
    sastojci: "100% svježa matična mliječ (royal jelly)",
    upotreba: "Pola kašičice ujutro, na prazan stomak. Staviti pod jezik i ostaviti da se otopi.",
    prednosti: ["Vitalnost", "Antiaging", "Hormonska ravnoteža", "Premium"],
    naStanju: true,
    novinkat: false,
    organsko: true,
    tezina: "20g",
  },
];

export const recenzije = [
  {
    id: "1",
    ime: "Amela Begić",
    lokacija: "Sarajevo, BiH",
    ocjena: 5,
    tekst: "Kamilica je fantastična! Svake večeri pripremi šalicu i spavam kao beba. Preporučujem svima.",
    proizvod: "Kamilica 60g",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&q=80",
  },
  {
    id: "2",
    ime: "Haris Mahmutović",
    lokacija: "Tuzla, BiH",
    ocjena: 5,
    tekst: "Crni kim je odličan! Mješam ga u jogurt svako jutro. Primijetio sam poboljšanje imuniteta tokom zime.",
    proizvod: "Crni kim mljeveni 100g",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80",
  },
  {
    id: "3",
    ime: "Jasmina Kovačević",
    lokacija: "Mostar, BiH",
    ocjena: 5,
    tekst: "Zahter je tačno onakav kakvog sam znala kod bake. Miris i okus su savršeni. Brza dostava, odlično pakovanje!",
    proizvod: "Zahter 90g",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80",
  },
  {
    id: "4",
    ime: "Edin Softić",
    lokacija: "Zenica, BiH",
    ocjena: 5,
    tekst: "Kupujem od Arifoğlua već godinu dana. Kvalitet je uvijek na vrhuncu. Šafran je bio posebno impresivan za cijenu.",
    proizvod: "Šafran (kutija) 2g",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80",
  },
];

export const prednosti = [
  {
    ikona: "Leaf",
    naslov: "100% Prirodno",
    opis: "Svaki sastojak je pažljivo nabavljen iz prirode, bez umjetnih aditiva.",
  },
  {
    ikona: "Award",
    naslov: "Certificirano organsko",
    opis: "Naša organska linija posjeduje međunarodnu certifikaciju za vaš mir.",
  },
  {
    ikona: "Zap",
    naslov: "Brza dostava",
    opis: "Narudžbe šaljemo u roku od 24 sata, dostava 3-5 radnih dana.",
  },
  {
    ikona: "ShieldCheck",
    naslov: "Testirano kvalitetno",
    opis: "Svaka serija je laboratorijski testirana na čistoću, jačinu i sigurnost.",
  },
];
